name: Java CI with Gradle

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Decode MYSQL
      env:
        MYSQL_DRIVER: ${{ secrets.MYSQL_DRIVER }}
        MYSQL_URL: ${{ secrets.MYSQL_URL }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: echo -e "mysql.driver=\"$MYSQL_DRIVER\"\nmysql.url=\"$MYSQL_URL\"\nmysql.username=\"$MYSQL_USERNAME\"\nmysql.password=\"$MYSQL_PASSWORD\"" > ./src/main/resources/application.properties

    
    - name: Setup MySQL 
      env:
        MYSQL_DRIVER: ${{ secrets.MYSQL_DRIVER }}
        MYSQL_URL: ${{ secrets.MYSQL_URL }}
        MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      uses: samin/mysql-action@v1 
      with: 
        character set server: 'utf8' 
        mysql database: 'kureal' 
        mysql user: ${{ secrets.MYSQL_USERNAME }} 
        mysql password: ${{ secrets.MYSQL_PASSWORD }} 

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew --version
        ./gradlew build # 빌드 
        
#     - name: Upload S3
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_KEY }}
#       run: |
#         aws s3 cp \
#           --region ap-northeast-2 \
#           ./build/libs/*.war s3://kurealdeploy
# 새로 추가 된 부분 
    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_UPLOAD }}
        aws-secret-access-key: ${{ secrets.AWS_S3_UPLOAD_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://kurealdeploy/$GITHUB_SHA.zip
      
    - name: Code Deploy
      run: aws deploy create-deployment --application-name logging-system-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=kurealdeploy,bundleType=zip,key=$GITHUB_SHA.zip

